on: [push]
name: ChatApp CICD

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

  PreBuild-Test:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@main
      - name: 'Run Pre-Build Tests'
        run: |
          echo "Running pre-build tests..."
          # Replace with actual test commands
          echo "Tests completed."

  Build:
    runs-on: ubuntu-latest
    needs: PreBuild-Test
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@main
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/chatapp:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/chatapp:${{ github.sha }}

  PreDeploy-Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@main
      - name: 'Run Pre-Deploy Tests'
        run: |
          echo "Running pre-deploy tests..."
          # Replace with actual test commands
          echo "Tests completed."

  Deploy:
    runs-on: ubuntu-latest
    needs: PreDeploy-Test
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@main
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/chatapp:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-chatapp
          location: 'east us'

  PostDeploy-Test:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@main
      - name: 'Run Post-Deploy Tests'
        run: |
          echo "Running post-deploy tests..."
          # Replace with actual test commands
          echo "Tests completed."
